MOODS = {
    1: {"name": "Terrified", "emoji": "😨", "score": 1},
    2: {"name": "Anxious", "emoji": "😰", "score": 1},
    3: {"name": "Worried", "emoji": "😟", "score": 1},
    4: {"name": "Sad", "emoji": "😔", "score": 2},
    5: {"name": "Lonely", "emoji": "😞", "score": 3},
    6: {"name": "Frustrated", "emoji": "😤", "score": 2},
    7: {"name": "Angry", "emoji": "😠", "score": 1},
    8: {"name": "Overwhelmed", "emoji": "😩", "score": 4},
    9: {"name": "Neutral", "emoji": "😐", "score": 5},
    10: {"name": "Content", "emoji": "🙂", "score": 8},
    11: {"name": "Happy", "emoji": "😊", "score": 10},
    12: {"name": "Excited", "emoji": "😄", "score": 6},
    13: {"name": "Grateful", "emoji": "❤️", "score": 10},
    14: {"name": "Peaceful", "emoji": "😌", "score": 8},
    15: {"name": "Proud", "emoji": "🤩", "score": 10},
    16: {"name": "Reflective", "emoji": "🤔", "score": 7},
}