"""Rename possible patterns to observations

Revision ID: 0b462c30ac78
Revises: 34db82d2afc9
Create Date: 2026-09-01 10:06:26.280784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b462c30ac78'
down_revision = '34db82d2afc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.drop_column('possible_patterns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('possible_patterns', sa.TEXT(), nullable=True))
        batch_op.drop_column('observations')

    # ### end Alembic commands ###
