"""Add therapy question answers

Revision ID: 34db82d2afc9
Revises: 9c3bb405b5a0
Create Date: 2026-08-28 13:30:53.464474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34db82d2afc9'
down_revision = '9c3bb405b5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapy_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapy_question', schema=None) as batch_op:
        batch_op.drop_column('answered_at')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
