"""Add compass_date to DailyCompass

Revision ID: 96d16744f7ca
Revises: 73f0c868c3cd
Create Date: 2026-08-05 18:04:57.324990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d16744f7ca'
down_revision = '73f0c868c3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_compass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compass_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_compass', schema=None) as batch_op:
        batch_op.drop_column('compass_date')

    # ### end Alembic commands ###
