"""Add reflection analysis fields

Revision ID: 9c3bb405b5a0
Revises: b593f917dc2e
Create Date: 2026-08-21 14:50:57.891396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3bb405b5a0'
down_revision = 'b593f917dc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflection_question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('overall_assessment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('concerns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('growth', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('practical_focus', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflection', schema=None) as batch_op:
        batch_op.drop_column('practical_focus')
        batch_op.drop_column('growth')
        batch_op.drop_column('concerns')
        batch_op.drop_column('overall_assessment')
        batch_op.drop_column('reflection_question')

    # ### end Alembic commands ###
